// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace Player
{
	namespace Ability
	{
		namespace Input
		{
			WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LMB);
			WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RMB);
			WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Q);
			WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Space);
		}
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Light);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Heavy);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability1);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jump);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attackable);
	}

	namespace Status
	{
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jumping);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attacking);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dead);
	}
}

namespace Shared
{
	namespace Event
	{
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MeleeHit);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TakeHit);
	}

	namespace SetByCaller
	{
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseDamageMultiplier)
	}
	
}

namespace GameplayCue
{
	namespace Shared
	{
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TakeHit)
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dead)
	}
}

namespace UI
{
	namespace Layer
	{
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameHUD);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MainMenu);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PauseMenu);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dialog);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LoadingScreen);
	}
}

namespace Session
{
	namespace Status
	{
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hosting);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Searching);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InSession);
	}
}
